version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    commit-message:
      prefix: "yocto: "
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      layers:
        patterns:
          - "bitbake"
          - "openembedded-core"
          - "meta-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
      actions:
        patterns:
          - "*"
