line-length = 119
exclude = [
    "bitbake",
    "meta-arm",
    "meta-labgrid",
    "meta-oe",
    "meta-ptx",
    "meta-rauc",
    "meta-selinux",
    "meta-virtualization",
    "openembedded-core",
]
lint.select = ["B", "E", "F", "I", "SIM"]
