# WARNING: this file is read by the tacd and used as a template to generate a
# version with additional update polling configuration.
# The original file is placed in `/usr/lib/rauc/system.conf`, while the runtime
# version is placed in `/run/rauc/system.conf`.
# The latter may not exist if polling is not enabled and thus no special
# runtime config is required.

[system]
compatible=Linux Automation GmbH - LXA TAC
bootloader=barebox
bundle-formats=-plain
data-directory=/srv/rauc

[keyring]
directory=/etc/rauc/certificates-enabled

[handlers]
system-info=/usr/lib/rauc/system-info-handler.sh

[streaming]
send-headers=boot-id;system-version;serial;transaction-id;uptime

# <tacd-polling-section>

[slot.rootfs.0]
device=/dev/disk/by-partuuid/e82e6873-62cc-46fb-90f0-3e936743fa62
type=ext4
bootname=system0
resize=true

[slot.rootfs.1]
device=/dev/disk/by-partuuid/8eb3e87e-2b4e-45e3-888b-2f678662862d
type=ext4
bootname=system1
resize=true

[slot.bootloader.0]
device=/dev/mmcblk1
type=boot-emmc

[log.all-log]
filename=all-events.log
