#!/bin/sh

# Turn the RGB status LED on with a blueish green
led led-status-red 0
led led-status-green 252
led led-status-blue 97

echo -a /dev/fbconsole0 -e -n "\e[?25l\e[1;1H\e[37;1mBooting root-a ..."

boot -v mmc1.root-a

# Show splash screen with red background on error
splash -b 0xffcd0000 /env/data/splash.png

echo -a /dev/fbconsole0 -e -n "\e[17;10H\e[41mError booting root-a!"
