# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.7.2 pointing at a commit from 2026-01-08 22:12:05 +0000
SRCBRANCH = "18-7-stable"
SRCREV = "1c855082f3c308de9ac1dd087202b611f4b9d368"
