# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.5.0 pointing at a commit from 2025-10-13 19:20:30 +0000
SRCBRANCH = "18-5-stable"
SRCREV = "bda84871762de5fb1573f4495940e044e8a5a010"
