# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.7.1 pointing at a commit from 2025-12-23 18:32:24 +0000
SRCBRANCH = "18-7-stable"
SRCREV = "cc7f92770f967be5f7d0f5612d6b131af3477a57"
