# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.6.1 pointing at a commit from 2025-11-20 22:34:41 -0800
SRCBRANCH = "18-6-stable"
SRCREV = "b5e9c6d04ecb017785f6d475dbc88868c7ff7fc1"
