# This file was generated by tools/update/update.py

require rkdeveloptool.inc

# Commit 304f073752fd25c854e1bcf05d8e7f925b1f4e14 created 2025-03-07 15:34:30 +0800
SRCBRANCH = "master"
SRCREV = "304f073752fd25c854e1bcf05d8e7f925b1f4e14"
