# This file was generated by tools/update/update.py

require qdl.inc

# Git tag v2.2 pointing at a commit from 2025-09-08 14:16:39 -0500
SRCBRANCH = "master"
SRCREV = "a601db1868bcda454a77b6769ca9efac3b0a114c"
