# This file was generated by tools/update/update.py

require qdl.inc

# Git tag v2.4 pointing at a commit from 2025-12-18 18:52:57 -0800
SRCBRANCH = "master"
SRCREV = "6eeb866b1503a9219258edbdb72fcd478c20b2d7"
