# This file was generated by tools/update/update.py

# Git tag bcu_1.1.124 pointing at a commit from 2025-11-05 15:03:30 +0800
SRCBRANCH = "master"
SRCREV = "98d4db41651e9e094a065baed105ce2c6fb8c86e"
PV = "1.1.124"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
