# This file was generated by tools/update/update.py

# Git tag bcu_1.1.123 pointing at a commit from 2025-10-22 18:12:10 +0800
SRCBRANCH = "master"
SRCREV = "783623ce26d5d4e3211ddf467ccf8d130edf81ad"
PV = "1.1.123"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
