# This file was generated by tools/update/update.py

# Git tag bcu_1.1.128 pointing at a commit from 2025-12-04 16:55:36 +0800
SRCBRANCH = "master"
SRCREV = "e7027dcb867dae7aebc8fd0a78ab13f05a4557f2"
PV = "1.1.128"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
