# This file was generated by tools/update/update.py

require ripgrep.inc

# Git tag 14.1.1 pointing at a commit from 2024-09-08 22:15:00 -0400
SRCBRANCH = "master"
SRCREV = "4649aa9700619f94cf9c66876e9549d83420e16c"
