# Auto-Generated by cargo-bitbake 0.3.15-alpha.0
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get ripgrep could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/ripgrep/12.1.1"
SRC_URI += "git://github.com/BurntSushi/ripgrep.git;protocol=https;nobranch=1"
SRCREV = "9c8d873a75ccb2a8d3ed692148becb2e72514732"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+9c8d873a75"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/aho-corasick/0.7.15 \
    crate://crates.io/atty/0.2.14 \
    crate://crates.io/autocfg/1.0.1 \
    crate://crates.io/base64/0.13.0 \
    crate://crates.io/bitflags/1.2.1 \
    crate://crates.io/bstr/0.2.14 \
    crate://crates.io/bytecount/0.6.2 \
    crate://crates.io/byteorder/1.4.2 \
    crate://crates.io/cc/1.0.66 \
    crate://crates.io/cfg-if/0.1.10 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/clap/2.33.3 \
    crate://crates.io/crossbeam-channel/0.5.0 \
    crate://crates.io/crossbeam-utils/0.8.1 \
    crate://crates.io/encoding_rs/0.8.26 \
    crate://crates.io/encoding_rs_io/0.1.7 \
    crate://crates.io/fnv/1.0.7 \
    crate://crates.io/fs_extra/1.2.0 \
    crate://crates.io/glob/0.3.0 \
    crate://crates.io/hermit-abi/0.1.18 \
    crate://crates.io/itoa/0.4.7 \
    crate://crates.io/jemalloc-sys/0.3.2 \
    crate://crates.io/jemallocator/0.3.2 \
    crate://crates.io/jobserver/0.1.21 \
    crate://crates.io/lazy_static/1.4.0 \
    crate://crates.io/libc/0.2.82 \
    crate://crates.io/libm/0.1.4 \
    crate://crates.io/log/0.4.13 \
    crate://crates.io/memchr/2.3.4 \
    crate://crates.io/memmap2/0.2.0 \
    crate://crates.io/num_cpus/1.13.0 \
    crate://crates.io/once_cell/1.5.2 \
    crate://crates.io/packed_simd_2/0.3.4 \
    crate://crates.io/pcre2-sys/0.2.5 \
    crate://crates.io/pcre2/0.2.3 \
    crate://crates.io/pkg-config/0.3.19 \
    crate://crates.io/proc-macro2/1.0.24 \
    crate://crates.io/quote/1.0.8 \
    crate://crates.io/regex-automata/0.1.9 \
    crate://crates.io/regex-syntax/0.6.22 \
    crate://crates.io/regex/1.4.3 \
    crate://crates.io/ryu/1.0.5 \
    crate://crates.io/same-file/1.0.6 \
    crate://crates.io/serde/1.0.119 \
    crate://crates.io/serde_derive/1.0.119 \
    crate://crates.io/serde_json/1.0.61 \
    crate://crates.io/strsim/0.8.0 \
    crate://crates.io/syn/1.0.58 \
    crate://crates.io/termcolor/1.1.2 \
    crate://crates.io/textwrap/0.11.0 \
    crate://crates.io/thread_local/1.1.2 \
    crate://crates.io/unicode-width/0.1.8 \
    crate://crates.io/unicode-xid/0.2.1 \
    crate://crates.io/walkdir/2.3.1 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.5 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.9 \
"

SRC_URI[aho-corasick-0.7.15.sha256sum] = "7404febffaa47dac81aa44dba71523c9d069b1bdc50a77db41195149e17f68e5"
SRC_URI[atty-0.2.14.sha256sum] = "d9b39be18770d11421cdb1b9947a45dd3f37e93092cbf377614828a319d5fee8"
SRC_URI[autocfg-1.0.1.sha256sum] = "cdb031dd78e28731d87d56cc8ffef4a8f36ca26c38fe2de700543e627f8a464a"
SRC_URI[base64-0.13.0.sha256sum] = "904dfeac50f3cdaba28fc6f57fdcddb75f49ed61346676a78c4ffe55877802fd"
SRC_URI[bitflags-1.2.1.sha256sum] = "cf1de2fe8c75bc145a2f577add951f8134889b4795d47466a54a5c846d691693"
SRC_URI[bstr-0.2.14.sha256sum] = "473fc6b38233f9af7baa94fb5852dca389e3d95b8e21c8e3719301462c5d9faf"
SRC_URI[bytecount-0.6.2.sha256sum] = "72feb31ffc86498dacdbd0fcebb56138e7177a8cc5cea4516031d15ae85a742e"
SRC_URI[byteorder-1.4.2.sha256sum] = "ae44d1a3d5a19df61dd0c8beb138458ac2a53a7ac09eba97d55592540004306b"
SRC_URI[cc-1.0.66.sha256sum] = "4c0496836a84f8d0495758516b8621a622beb77c0fed418570e50764093ced48"
SRC_URI[cfg-if-0.1.10.sha256sum] = "4785bdd1c96b2a846b2bd7cc02e86b6b3dbf14e7e53446c4f54c92a361040822"
SRC_URI[cfg-if-1.0.0.sha256sum] = "baf1de4339761588bc0619e3cbc0120ee582ebb74b53b4efbf79117bd2da40fd"
SRC_URI[clap-2.33.3.sha256sum] = "37e58ac78573c40708d45522f0d80fa2f01cc4f9b4e2bf749807255454312002"
SRC_URI[crossbeam-channel-0.5.0.sha256sum] = "dca26ee1f8d361640700bde38b2c37d8c22b3ce2d360e1fc1c74ea4b0aa7d775"
SRC_URI[crossbeam-utils-0.8.1.sha256sum] = "02d96d1e189ef58269ebe5b97953da3274d83a93af647c2ddd6f9dab28cedb8d"
SRC_URI[encoding_rs-0.8.26.sha256sum] = "801bbab217d7f79c0062f4f7205b5d4427c6d1a7bd7aafdd1475f7c59d62b283"
SRC_URI[encoding_rs_io-0.1.7.sha256sum] = "1cc3c5651fb62ab8aa3103998dade57efdd028544bd300516baa31840c252a83"
SRC_URI[fnv-1.0.7.sha256sum] = "3f9eec918d3f24069decb9af1554cad7c880e2da24a9afd88aca000531ab82c1"
SRC_URI[fs_extra-1.2.0.sha256sum] = "2022715d62ab30faffd124d40b76f4134a550a87792276512b18d63272333394"
SRC_URI[glob-0.3.0.sha256sum] = "9b919933a397b79c37e33b77bb2aa3dc8eb6e165ad809e58ff75bc7db2e34574"
SRC_URI[hermit-abi-0.1.18.sha256sum] = "322f4de77956e22ed0e5032c359a0f1273f1f7f0d79bfa3b8ffbc730d7fbcc5c"
SRC_URI[itoa-0.4.7.sha256sum] = "dd25036021b0de88a0aff6b850051563c6516d0bf53f8638938edbb9de732736"
SRC_URI[jemalloc-sys-0.3.2.sha256sum] = "0d3b9f3f5c9b31aa0f5ed3260385ac205db665baa41d49bb8338008ae94ede45"
SRC_URI[jemallocator-0.3.2.sha256sum] = "43ae63fcfc45e99ab3d1b29a46782ad679e98436c3169d15a167a1108a724b69"
SRC_URI[jobserver-0.1.21.sha256sum] = "5c71313ebb9439f74b00d9d2dcec36440beaf57a6aa0623068441dd7cd81a7f2"
SRC_URI[lazy_static-1.4.0.sha256sum] = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646"
SRC_URI[libc-0.2.82.sha256sum] = "89203f3fba0a3795506acaad8ebce3c80c0af93f994d5a1d7a0b1eeb23271929"
SRC_URI[libm-0.1.4.sha256sum] = "7fc7aa29613bd6a620df431842069224d8bc9011086b1db4c0e0cd47fa03ec9a"
SRC_URI[log-0.4.13.sha256sum] = "fcf3805d4480bb5b86070dcfeb9e2cb2ebc148adb753c5cca5f884d1d65a42b2"
SRC_URI[memchr-2.3.4.sha256sum] = "0ee1c47aaa256ecabcaea351eae4a9b01ef39ed810004e298d2511ed284b1525"
SRC_URI[memmap2-0.2.0.sha256sum] = "e73be3b7d04a0123e933fea1d50d126cc7196bbc0362c0ce426694f777194eee"
SRC_URI[num_cpus-1.13.0.sha256sum] = "05499f3756671c15885fee9034446956fff3f243d6077b91e5767df161f766b3"
SRC_URI[once_cell-1.5.2.sha256sum] = "13bd41f508810a131401606d54ac32a467c97172d74ba7662562ebba5ad07fa0"
SRC_URI[packed_simd_2-0.3.4.sha256sum] = "3278e0492f961fd4ae70909f56b2723a7e8d01a228427294e19cdfdebda89a17"
SRC_URI[pcre2-sys-0.2.5.sha256sum] = "dec30e5e9ec37eb8fbf1dea5989bc957fd3df56fbee5061aa7b7a99dbb37b722"
SRC_URI[pcre2-0.2.3.sha256sum] = "85b30f2f69903b439dd9dc9e824119b82a55bf113b29af8d70948a03c1b11ab1"
SRC_URI[pkg-config-0.3.19.sha256sum] = "3831453b3449ceb48b6d9c7ad7c96d5ea673e9b470a1dc578c2ce6521230884c"
SRC_URI[proc-macro2-1.0.24.sha256sum] = "1e0704ee1a7e00d7bb417d0770ea303c1bccbabf0ef1667dae92b5967f5f8a71"
SRC_URI[quote-1.0.8.sha256sum] = "991431c3519a3f36861882da93630ce66b52918dcf1b8e2fd66b397fc96f28df"
SRC_URI[regex-automata-0.1.9.sha256sum] = "ae1ded71d66a4a97f5e961fd0cb25a5f366a42a41570d16a763a69c092c26ae4"
SRC_URI[regex-syntax-0.6.22.sha256sum] = "b5eb417147ba9860a96cfe72a0b93bf88fee1744b5636ec99ab20c1aa9376581"
SRC_URI[regex-1.4.3.sha256sum] = "d9251239e129e16308e70d853559389de218ac275b515068abc96829d05b948a"
SRC_URI[ryu-1.0.5.sha256sum] = "71d301d4193d031abdd79ff7e3dd721168a9572ef3fe51a1517aba235bd8f86e"
SRC_URI[same-file-1.0.6.sha256sum] = "93fc1dc3aaa9bfed95e02e6eadabb4baf7e3078b0bd1b4d7b6b0b68378900502"
SRC_URI[serde-1.0.119.sha256sum] = "9bdd36f49e35b61d49efd8aa7fc068fd295961fd2286d0b2ee9a4c7a14e99cc3"
SRC_URI[serde_derive-1.0.119.sha256sum] = "552954ce79a059ddd5fd68c271592374bd15cab2274970380c000118aeffe1cd"
SRC_URI[serde_json-1.0.61.sha256sum] = "4fceb2595057b6891a4ee808f70054bd2d12f0e97f1cbb78689b59f676df325a"
SRC_URI[strsim-0.8.0.sha256sum] = "8ea5119cdb4c55b55d432abb513a0429384878c15dde60cc77b1c99de1a95a6a"
SRC_URI[syn-1.0.58.sha256sum] = "cc60a3d73ea6594cd712d830cc1f0390fd71542d8c8cd24e70cc54cdfd5e05d5"
SRC_URI[termcolor-1.1.2.sha256sum] = "2dfed899f0eb03f32ee8c6a0aabdb8a7949659e3466561fc0adf54e26d88c5f4"
SRC_URI[textwrap-0.11.0.sha256sum] = "d326610f408c7a4eb6f51c37c330e496b08506c9457c9d34287ecc38809fb060"
SRC_URI[thread_local-1.1.2.sha256sum] = "d8208a331e1cb318dd5bd76951d2b8fc48ca38a69f5f4e4af1b6a9f8c6236915"
SRC_URI[unicode-width-0.1.8.sha256sum] = "9337591893a19b88d8d87f2cec1e73fad5cdfd10e5a6f349f498ad6ea2ffb1e3"
SRC_URI[unicode-xid-0.2.1.sha256sum] = "f7fe0bb3479651439c9112f72b6c505038574c9fbb575ed1bf3b797fa39dd564"
SRC_URI[walkdir-2.3.1.sha256sum] = "777182bc735b6424e1a57516d35ed72cb8019d85c8c9bf536dccb3445c1a2f7d"
SRC_URI[winapi-i686-pc-windows-gnu-0.4.0.sha256sum] = "ac3b87c63620426dd9b991e5ce0329eff545bccbbb34f3be09ff6fb6ab51b7b6"
SRC_URI[winapi-util-0.1.5.sha256sum] = "70ec6ce85bb158151cae5e5c87f95a8e97d2c0c4b001223f33a334e3ce5de178"
SRC_URI[winapi-x86_64-pc-windows-gnu-0.4.0.sha256sum] = "712e227841d057c1ee1cd2fb22fa7e5a5461ae8e48fa2ca79ec42cfc1931183f"
SRC_URI[winapi-0.3.9.sha256sum] = "5c839a674fcd7a98952e593242ea400abe93992746761e38641405d28b00f419"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE-MIT;md5=8d0d0aa488af0ab9aafa3b85a7fc8e12 \
    file://UNLICENSE;md5=7246f848faa4e9c9fc0ea91122d6e680 \
"

SUMMARY = "ripgrep is a line-oriented search tool that recursively searches your current \
directory for a regex pattern while respecting your gitignore rules. ripgrep \
has first class support on Windows, macOS and Linux."
HOMEPAGE = "https://github.com/BurntSushi/ripgrep"
LICENSE = "Unlicense | MIT"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include ripgrep-${PV}.inc
include ripgrep.inc
