# This file was generated by tools/update/update.py

require github-act-runner.inc

# Git tag v0.12.1 pointing at a commit from 2025-12-23 20:31:24 +0100
SRCBRANCH = "main"
SRCREV = "bb067210cce62c683c8ad3425fc0f90a280dabb6"
