# This file was generated by tools/update/update.py

require github-act-runner.inc

# Git tag v0.12.2 pointing at a commit from 2026-01-07 23:46:41 +0100
SRCBRANCH = "main"
SRCREV = "f0ff9b6abcbb4b342954a4d02319d5b1a8afb171"
