# This file was generated by tools/update/update.py

require github-act-runner.inc

# Git tag v0.12.0 pointing at a commit from 2025-09-12 15:58:57 +0000
SRCBRANCH = "main"
SRCREV = "1636dd12fe3f21f235a673aef773eaf2853b6ce2"
