name: codespell

on:
  pull_request:
  push:
  schedule:
    - cron: '10 21 * * 4'

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: python3 -m pip install codespell
      - run: codespell .
