# This file was generated by tools/update/update.py

require imx-uuu.inc

# Git tag uuu_1.5.233 pointing at a commit from 2025-08-25 09:28:25 -0500
SRCBRANCH = "master"
SRCREV = "79ce7d2b2e7459e7b7c94f902d172c30b08884ab"
