# This file was generated by tools/update/update.py

require imx-uuu.inc

# Git tag uuu_1.5.243 pointing at a commit from 2025-12-16 09:28:39 -0500
SRCBRANCH = "master"
SRCREV = "230f1b150eb7f9ea906a0138c0e28240a8e2df8f"
