# This file was generated by tools/update/update.py

require imx-uuu.inc

# Git tag uuu_1.5.239 pointing at a commit from 2025-10-29 09:09:34 -0500
SRCBRANCH = "master"
SRCREV = "051561b5bf64e5befbdd1c9fe9b414a5c9570d74"
