# This file was generated by tools/update/update.py

require bottom.inc

# Git tag 0.10.2 pointing at a commit from 2024-08-05 20:28:17 -0400
SRCBRANCH = "main"
SRCREV = "2ec1fb56c9db0b37acc4eca3230adfb52720376b"
